### ISSUE TITLE
The pdf and the open button not showing up

### ISSUE THREAD

**Issue by roy-abhi-roy** [e-zz/logseq-pdf-extract#8] opened 2024-01-14 14:43 UTC
I am getting this error: the pdf is not showing, and also the open button function is not working,  <img width="363" alt="image" src="https://github.com/e-zz/logseq-pdf-extract/assets/95222112/9c00b193-5c40-4a21-832c-9de2287734bb">;

However, when I am using the normal `/zotero` plugin, then I am not having issues! 
<img width="604" alt="image" src="https://github.com/e-zz/logseq-pdf-extract/assets/95222112/01ef1674-f8e4-4a68-a469-709520cf3998">

Could you please provide me with guidance on how to resolve this issue? Thank you.

**Comment by e-zz** [comment] 2024-01-14 15:45
Hi, thanks for using this plugin and helping me test it by reporting the issue here.

The first thing is to check if you have installed the latest release of [ZotServer](https://github.com/e-zz/ZotServer/releases/latest) in your Zotero client. 
- There was some bug with the automatic update menachism. It's been fixed after version 1.0.4. But if you have older version installed, I am sorry you have to manually install ZotServer v1.0.4 . Then it should be Ok.

If you already installed ZotServer v1.0.4 in Zotero, then I will need more information to understand what's wrong for this item. These might be helpful
- **the type of the button**: go to the block you've shown, enter edit mode, and check if it's a zotero-linked-file or zotero-imported-file
- **Error messages in Logseq console**: Press "ctrl+shift+i" to show the Logseq console. Then we want to catch any error message appearing when importing the item with this plugin. To do this, please 
    - delete the Logseq page already imported, then import it with plugin
    - or rename the title of the item in Zotero, then import it with plugin
- provide the pdf or link to the file online, like doi or arxiv id, so I could do a more thourough test on my side.

If you have the time to collect and provide any information I mentioned above, I could be able to look into this. Thanks!

**Comment by roy-abhi-roy** [comment] 2024-01-16 07:33
Thank you so much for your reply, but I cannot fix the issue.
Yes, I am using ZotServer v1.0.4. The plugin works flawlessly for some articles, but it does not work for **_most_** articles.
<img width="200" alt="image" src="https://github.com/e-zz/logseq-pdf-extract/assets/95222112/4ae698c2-125f-4024-8d50-2bfb4dff3d7a">, 
**Here are two examples of pages: one that works and another that doesn't work.**

The one in which it is not working shows the following:
<img width="300" alt="image" src="https://github.com/e-zz/logseq-pdf-extract/assets/95222112/4121a54a-48dc-4259-b791-2393b5ec6a76">, 
an example doi for the link which is not working is https://www.science.org/doi/10.1126/science.1246164

**Comment by e-zz** [comment] 2024-01-16 22:15
> Thank you so much for your reply, but I cannot fix the issue. ....

Thanks for the information.
I just checked with the doi. However, I failed to reproduce the issue. I only have access to win10 and linux (Ubuntu 22.04). I don't know if you use Macos or other distribution of linux. 
Anyway, to better understand the situation, I just updated the plugin and added a `debug_zotero` option. Please check with the item again as below. In Logseq, 

1. upgrade Logseq-PDF-Extract plugin to the latest (0.0.9) in Logseq
2. enable debug mode in the plugin settings
    > <img src="https://github.com/e-zz/logseq-pdf-extract/assets/37920155/44bd3e07-c949-4c26-aec0-1487d1cbcac4" alt="image" width="75%">

3. reload Logseq by `ctrl+r` (on default) or just reopen Logseq
4. import the item at cursor from search panel 
    - or by selection in Zotero and `ctrl+alt+e`
    - No need to delete the item page before importing it at cursor
    > <img src="https://github.com/e-zz/logseq-pdf-extract/assets/37920155/b7cc93d6-b56c-4235-8a3e-91c5a06cec31" alt="image" width="60%">



5. open DevTools in Logseq by pressing `ctrl+shift+i` (or `alt+shift+i` if not working)  and check the messages in DevTools **console** tab. 
    - On my side, it looks like this
    > ![image](https://github.com/e-zz/logseq-pdf-extract/assets/37920155/4f89682c-5f95-4c38-bc1b-f0c2d24b36de)

**Comment by e-zz** [comment] 2024-01-19 10:06
Hi again! 
I doubt the problem is actually from url attachments. These files were actually not imported and thus, shown as "undefined". If that's the cause behind the mess, you should be able to fix it by upgrading the plugin to v0.0.10 which allows to import url attachments as well as PDFs. 
Hope this helps!

**Comment by roy-abhi-roy** [comment] 2024-01-19 14:32
Thank you so much for your reply
I upgraded the plugin to version 0.010. Now the "open" button appears and the undefined has also been fixed. Thank you for your help in resolving the issue! 🎉🎉

-----
PS: I was wondering if there is a way to customize which fields I can include in the properties of the page, having all the properties makes it so long. Is there a way to select which properties to be imported (because some of the properties are irrelevant)? 
<img width="155" alt="image" src="https://github.com/e-zz/logseq-pdf-extract/assets/95222112/66ebed95-251f-46b8-9a15-f2bd74905803">

Also, is it possible to have a template for the pages, like the one in this https://github.com/sawhney17/logseq-citation-manager


Thank you so much for taking the time to look into my query. I really appreciate it. Thanks!

**Comment by e-zz** [comment] 2024-01-22 09:24
> Thank you so much for your reply I upgraded the plugin to version 0.010. Now the "open" button appears and the undefined has also been fixed. Thank you for your help in resolving the issue! 🎉🎉
> 
> PS: I was wondering if there is a way to customize which fields I can include in the properties of the page, having all the properties makes it so long. Is there a way to select which properties to be imported (because some of the properties are irrelevant)? <img alt="image" width="155" src="https://private-user-images.githubusercontent.com/95222112/298093044-66ebed95-251f-46b8-9a15-f2bd74905803.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTQ2MTUsIm5iZiI6MTcwNTkxNDMxNSwicGF0aCI6Ii85NTIyMjExMi8yOTgwOTMwNDQtNjZlYmVkOTUtMjUxZi00NmI4LTlhMTUtZjJiZDc0OTA1ODAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA5MDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3ODRhNjZhNzI3NDUzYWU3NWE5Zjc3ZjI2ZmFjMTg3M2NkOGJmYmNiYTJhN2EwMjBmNjcyODE1OGE4YTlhMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nDx3Owp4SCac2-RCblA7w8nL4hdnoj0ndwR53eE136Q">
> 
> Also, is it possible to have a template for the pages, like the one in this https://github.com/sawhney17/logseq-citation-manager
> 
> Thank you so much for taking the time to look into my query. I really appreciate it. Thanks!

Glad to know it works for you. I will now close this issue for clarity.

- For item page properties, it should be easy to customize which to be imported and which to omit.  Probably we can have the "properties filter" feature in the next release. 
- As for the template you mentioned, I might need more information on the feature to decide if we should imeplement it. Please open a dedicated FR page for the template feature, so we could keep our relevant discussions there.

**Closed by e-zz** 2024-01-22 09:24 UTC

**Comment by e-zz** [comment] 2024-01-29 18:11
The property filter has been added into the plugin version 0.0.11.
And I opened a discussion #10 for the template function you mentioned

**Comment by roy-abhi-roy** [comment] 2024-02-02 01:27
Hey, Thank you so much for the filter. It is really helpful to get rid of unnecessary keys. Thanks :)
